### ISSUE TITLE
use enclosed character for table/column names

### ISSUE THREAD

**Issue by fpriyatna** [oeg-upm/MIRROR#2]
use enclosed character for table/column names.
For example, use character `in mysql, as in`co-authors`,`student-sport`

**Comment by fpriyatna** [comment]
Mappings should be database-independent, the enclosed character will be generated by the R2RML engine (morph-RDB)

**Comment by fpriyatna** [comment]
Use \" as the enclosed character in mappings.

See: http://www.w3.org/2001/sw/rdb2rdf/test-cases/#R2RMLTC0011b

**Comment by lfm0006** [comment]
Hola Freddy


It seems that in issue 2, reported by Ernesto, MIRROR is trying to generate an object property like "AdministratorsHasAdministrators". If true, we must block this kind of property.


Issues 1 and 3 are more simple to fix.


Regards,

Luciano


________________________________
De: Freddy Priyatna <notifications@github.com>
Enviado: quinta-feira, 12 de fevereiro de 2015 11:37
Para: oeg-upm/MIRROR
Assunto: Re: [MIRROR] use enclosed character for table/column names (#2)


Closed #2<https://github.com/oeg-upm/MIRROR/issues/2>.

-
Reply to this email directly or view it on GitHub<https://github.com/oeg-upm/MIRROR/issues/2#event-234667156>.

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________
